import { execSync } from "node:child_process";
import { readFileSync, rmSync, writeFileSync } from "node:fs";

const input = "src/theme/input.css";
const tmp = "src/theme/.styles.out.css";
const out = "src/theme/styles.css.ts";

try {
  execSync(`pnpm exec tailwindcss -i ${input} -o ${tmp} --minify`, { stdio: "inherit" });
} catch {
  // Some environments expose the bin under the package name instead.
  execSync(`pnpm exec @tailwindcss/cli -i ${input} -o ${tmp} --minify`, { stdio: "inherit" });
}

const css = readFileSync(tmp, "utf8");
writeFileSync(
  out,
  `// GENERATED by scripts/build-styles.mjs — do not edit\nexport const stylesCss = ${JSON.stringify(css)};\n`,
);
rmSync(tmp);
console.log(`styles.css.ts written (${css.length} bytes)`);
